# Generated by Django 3.2.4 on 2024-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('normal', 'Normal'), ('example', 'Example'), ('other', 'Other')], default='normal', max_length=32),
        ),
    ]
